title = "[Co děláme? ...]"
author = "Petr Borkovec"
lang = "cs"
year = 1997
poem = """
Co děláme? Zabýváme se prostorem,
mlčíme, mrtvé necháváme spát.
Řežeme stromy, ohrazujem kompost,
chycené myši vyklápíme z pastí.
Večeři nosíme si do zahrady,
do pokoje si odnášíme chvojí.
Žluté ho navracíme zahradnímu ohni,
sladký kouř se nám válí v šatnících.
Vpodvečer z okna pozorujem zeď,
mluvíme tak, že mrtvé nebudíme.
Mezi nábytkem se spolu milujeme
těly, jež nejsou opak prostoru.
"""

[translation-1]
title = "[We do what?]"
translator = "Justin Quinn"
translator_level = "professional"
poem = """
We do what? We are involved in space,
are silent, we let the dead sleep on.
We cut down trees, fence off compost,
pry open traps where mice have come to grief.
We take our dinner out to the garden,
bring brushwood back into the room.
We return it yellowed to the bonfire,
its sweet smoke billowing through our wardrobes.
In the twilight we look out at the wall
and speak so as not to wake the dead.
Amidst the furniture we make love
with bodies, which are not the opposite of space.
"""