title = "Sbohem a šáteček"
author = "Vítězslav Nezval"
lang = "cs"
year = 1934
poem = """
Sbohem a kdybychom se nikdy nesetkali
bylo to překrásné a bylo toho dost
Sbohem a kdybychom si spolu schůzku dali
možná že nepřijdem že přijde jiný host

Bylo to překrásné žel všecko má svůj konec
Mlč umíráčku mlč ten smutek já už znám
Polibek kapesník siréna lodní zvonec
tři čtyři úsměvy a potom zůstat sám

Sbohem a kdybychom si neřekli už více
ať po nás zůstane maličká památka
vzdušná jak kapesník prostší než pohlednice
a trochu mámivá jak vůně pozlátka

A jestli viděl jsem co neviděli jiní
tím lépe vlaštovko jež hledáš rodný chlév
Ukázalas mi jih kde máš své hnízdo v skříni
Tvým osudem je let mým osudem je zpěv

Sbohem a bylo-li to všecko naposledy
tím hůře mé naděje nic vám už nezbude
Chcem-li se setkati nelučme se radš tedy
Sbohem a šáteček Vyplň se osude!
"""

[translation-1]
title = "Farewell and a Handkerchief"
translator = "Václav Z. J. Pinkava"
translator_level = "professional"
poem = """
Goodbye and if we should not ever meet anew
it really was delightful and quite enough for some
Goodbye and if we should yet make a rendezvous
maybe instead of us another guest will come

It really was delightful but everything has an end
Hush tolling bell I know that sadness from before
A kiss a napkin siren ship's bell to portend
three or four smiles and then to be alone once more

Goodbye and if we should not ever speak again
let there be something left a keepsake what we meant
as airy as a napkin more than a postcard plain
with suppositious scent of gilded ornament

And if I chanced to notice what others did not see
so much the better swift as you seek your home byre
You have shown me the south your nest there in etui
Your fate is flight my fate is song without a lyre

Goodbye and if this shall have been the final call
so much the worse my hope and nothing left all-told
If we would meet again then best not part at all
Goodbye and silken wave Let fate fulfilled unfold!
"""

[translation-2]
title = "Farewell and a Handkerchief"
translator = "Roman Kostovski"
translator_level = "professional"
poem = """
Farewell, and if we no longer meet
Our time was marvelous—we've shared enough
Farewell, and soon our trysts will be
With someone new, someone else's love

Our time was marvelous but all things end
Be silent knell your sorrow is quite clear
A kiss, a handkerchief, a ship's bell, a siren
One last smile as we part from here

Farewell and if we never speak again
Let a small memory of us unfold
Lighter than a handkerchief fluttering in the wind
Tempting as the scent of gleaming gold

And if I've seen what no one's seen before
That's for the best. Swallow, seek your native barn!
You've shown me the south where you'll nest once more
Your destiny's flight, my destiny's song

Farewell, and if it's for the last time
So much for my hopes—nothing else is left
But if you wish to meet again, don't say goodbye
Leave it to fate! Farewell and a handkerchief!
"""

[translation-3]
title = "Farewell and a Handkerchief"
translator = "Vilém Zouhar"
translator_level = "amateur"
poem = """
Farewell and if we never meet again
it was beautiful and it was a lot
Farewell and if to meet we arrange
maybe someone else will come and we will not.

It was beautiful, alas everything has its end
Stay silent, passing bell, I know the sorrow all to well
Being left alone after a three-four smiles mend
A kiss, a handkerchief, a siren a ship's bell.

Farewell and if we talk no more
of all of us let a small memento remain
airy as a handkerchief, plain as a postcard on the floor
and little intoxicating as the scent of golden cane.

And if we saw what others did not
the better, swallow who seeks your anchor ring
You showed me the south where in a wardrobe you squat
your destiny is to fly, mine is to sing.

Farewell and if all this was for the last time
these hardships, my hopes will not have prevailed
Should we mean to meet again, goodbyes are not prime
Farewell and a handkerchief. Destiny be fulfilled.
"""
