title = "Schwarze Katze"
author = "Rainer Maria Rilke"
lang = "de"
year = 1918
poem = """
Ein Gespenst ist noch wie eine Stelle,
dran dein Blick mit einem Klange stößt;
aber da, an diesem schwarzen Felle
wird dein stärkstes Schauen aufgelöst:

wie ein Tobender, wenn er in vollster
Raserei ins Schwarze stampft,
jählings am benehmenden Gepolster
einer Zelle aufhört und verdampft.

Alle Blicke, die sie jemals trafen,
scheint sie also an sich zu verhehlen,
um darüber drohend und verdrossen
zuzuschauern und damit zu schlafen.

Doch auf einmal kehrt sie, wie geweckt,
ihr Gesicht und mitten in das deine:
und da triffst du deinen Blick im geelen
Amber ihrer runden Augensteine
unerwartet wieder: eingeschlossen
wie ein ausgestorbenes Insekt. 
"""

[translation-1]
title = "The Black Cat"
translator = "allpoetry.net"
translator_level = "unknown"
poem = """
A ghost, though invisible, still is like a place
your sight can knock on, echoing; but here
within this thick black pelt, your strongest gaze
will be absorbed and utterly disappear:

just as a raving madman, when nothing else
can ease him, charges into his dark night
howling, pounds on the padded wall, and feels
the rage being taken in and pacified.

She seems to hide all looks that have ever fallen
into her, so that, like an audience,
she can look them over, menacing and sullen,
and curl to sleep with them. But all at once

as if awakened, she turns her face to yours;
and with a shock, you see yourself, tiny,
inside the golden amber of her eyeballs
suspended, like a prehistoric fly.
"""

[translation-2]
title = "The Black Cat"
translator = "Paul Archer"
translator_level = "professional"
poem = """
A spectre is still something
your eyes can hit with a clang;
but there, within that black fur,
your hardest stare dissolves:

just as a madman in full frenzy
stomping in the darkness,
suddenly at the cushioned wall
of a cell stops and simmers down.

All the looks she's ever been given
she seems to hide within herself
to watch over them with sullen
menace and sleep with them.

But suddenly, as if woken up,
she turns her face right into yours:
and then there's a second shock as
you meet your gaze in the amber
resin of her round eyes; trapped
inside like an extinct insect.
"""


[translation-3]
title = "The Black Cat"
translator = "Vilém Zouhar (Paul Archer post-edited)"
translator_level = "amateur (post-edited)"
poem = """
A spectre is still something like a place
your eyes can hit with a clang;
but there, within that black fur chase,
your hardest stare dissolves without a bang

just as a madman in a full frenzy call
stomping while the darkness awaits,
suddenly at the cushioned wall
of a prison cell that evaporates.

All the looks she's ever received
she seems to hide within
to watch over them - grieved
menace and with them to sleep in

But suddenly, as if awoken,
she turns her face right into yours:
and then there's a second shock, broken
as you meet your gaze in the amber doors
of her round eyes; trapped unspoken
inside like an extinct insect corpse.
"""
