title = "První Koncert"
author = "Antonín Sova"
lang = "cs"
year = 1890
poem = """
Již vystoup' v černém šatě bledý
a slech' jak hovor pod ním stichal,
vzduch parfumy a horkem dýchal,
sál světly hořel tmavohnědý. —

A dole před ním jako v pýří
v hedvábí, krajkách, musselinu,
půl ve světle a zpola v stínu,
dam řad se v polokruhu šíří.

Vlas tmavý, zlatý, vše to splývá;
ty žhavé oči, rudé rety!
Hle černých fraků silhouetty
hle, lorgnetů skla žádostivá!

Vznes' housle a již tóny spijí
vzduch stišený svou hloubkou plnou,
v klavíru akkord měkkou vlnou
vpad' jásavě a s energií. —

Však mistr jeho, kdysi slavný
se rozechvěn kams v chodby ztratil,
jej pocit strachu náhle schvátil,
vzpomínal na svůj debut dávný.

Ctěl uniknouti kritik hlasu,
i potlesku i hanobení,
i závisti, jež zub svůj cení,
a chce-li, do prachu rve krásu.

A zas jej v sál to pudí, žene;
jak třesou se ty ruce svadlé! —
Zda při tom někdo na zapadlé
se jméno jeho rozpomene?
"""

[translation-1]
title = "The First Concert"
translator = "Paul Selver"
translator_level = "professional"
poem = """
Pallid, in black array he strode
And marked the hush beneath his feet,
The air breathed perfume out and heat,
The hall with russet lustre glowed. —

Gossamer-like before him shed.
In muslin, silk and lace arrayed,
Half in the light and half in shade,
Ladies in semi-circle spread.

Billows of dark and golden hair;
These scarlet lips, these eyes on fire!
See, silhouettes of black attire,
See, the lorgnettes with gloating stare!

His violin with dazing spell
Grips the hushed air in deep refrains,
From the piano gentle strains
In waves of joy and potence fell. —

His master, whose renown is o'er
Astray within some passage quakes,
In sudden dread within him wakes
His debut in the days of yore.

Critics to shun was his desire,
Their infamy and their applause,
Their hatred with its gaping jaws,
Whose will drags beauty in the mire. 

Constrained afresh, he seeks the hall;
His shrivelled fingers, how they quiver! —
Perchance that someone will deliver
His name this evening from its fall? 
"""