title = "Pohled Smrti"
author = "Otakar Březina"
lang = "cs"
year = 1895
poem = """
U hlav lože a v soumracích tušení, mnohokrát, vím,
pohled můj zhasínal před vítězným pohledem tvým.

V mém slabosť a touha, smích ocele blyštící v tvém,
a v jeho zrcadle myšlénku vlastní uviděl jsem.

Šla bledá a zmatená v dálku zavátých neznámých Měst
do šera a polárních nocí němou únavou cest.

Úzkosť nejistoty tuhla jí v tvář a věčných prostorů chlad
na zmučené údy spínal jí, umdlené, kovový šat.

V záhyby mizících tvarů mlhami ze zraků tvých,
jak z květu mystického stromu střásal se přívalem sníh,

a houštl a temněl, zář do sebe vpíjel a šlehal a vál,
na ranách mé myšlenky jak v narudlých plamenech tál.

U hlav lože a v soumracích tušení, mnohokrát, vím,
pohled můj zhasínal před utkvělým pohledem tvým.

Jak somnambul svedený z lože, bledý, spoután a něm
pod hypnosou Nepoznaného jdu se svým snem

a přede mnou chví se v umdlených rukou mých dní,
zraky tvými rozžatá světla pohřebních pochodní.
"""

[translation-1]
title = "Gaze of Death"
translator = "Paul Selver"
translator_level = "professional"
poem = """
At bed-sides, in dusk of forebodings, many a time, I know,
Before thy conquering gaze has my gaze been laid low.

In mine was frailness and yearning, flashing steel's mirth in thine,
And in its mirror my own pondering I could divine.

To far-hidden, unknown cities, pale and bewildered it went
In gloom and polar nights with journeyings mute and forspent.

It stared with anguish of doubt, and the cold of eternal space
Its tortured and wearied limbs in a metal garb did enlace.

Mid folds of vanishing shapes from thine eyes through misty rifts
As from bloom of a mystical tree snow was scattered in drifts,

And thickened and darkened, and quaffing of lustre it scoured and gnawed
At scars of my ponderings, as in flames it crimsonly thawed.

At bed-sides, in dusk of forebodings, many a time, I know
Before thy motionless gaze has my gaze been laid low.

As a sleep-walker lured from his bed, pallid, fettered and dumb
My dream do I follow, and me an Unknown's promptings benumb.

And in wearied hands of my days, aquiver before me arise
Lights of funeral torches enkindled by thine eyes.
"""