title = "Chůze po dunách"
author = "Kateřina Rudčenková"
lang = "cs"
year = 2013
poem = """
I když jsi cítila dojetí
nad prudkým odstínem zeleně,
stromů a trav a borovicového podrostu,

i když tě dojímala nostalgie dýmu toho léta,
pálené trávy a pečených ryb,

i když tě dojímaly děti,
které ještě nic netušíce o restrikcích světa
už teď skákaly
po dlaždicích jen jedné barvy,

přesto pod tím vším dojetím
zůstávalas ve zklamání chladná
jako ledová tůňka v sibiřském lese.

Otáčela ses, aby ses ujistila,
že stopy vytlačené do břehu už jsou smyty,
smyty, nebylas. Nechtělas být,
nechtěla ses už do ničeho otiskovat.
"""

[translation-1]
title = "[We do what?]"
translator = "Walking on dunes"
translator_level = "professional"
poem = """
Even though you were moved
by the abrupt shade of green
of trees and grass and pine-tree undergrowth

even though you were moved by this summer's nostalgia of smoke
burning grass and grilled fish

even though you were moved by the children
who, as yet innocent of the restrictions of the world
already skipped from one tile of the same colour to another

despite all that emotion 
you remained cold underneath in your disappointment
like an icy pond in a Siberian forest.

You kept turning to make sure
that footprints left in the sand had been washed away
washed away, you were not. You didn't want to be
you didn't want to leave your imprint in anything at all.
"""