title = "Zaživa"
author = "Jaromír Typlt "
lang = "cs"
year = 2007
poem = """
Píšu o tom
a nechci na to myslet

Nemám potuchy
proč se vždycky upnu na jedno slovo
nějaké takové slovo
na kterém nakonec ztroskotám

„To se ti stalo ještě

            zaživa?“

            Toho odpoledne jsem se v tom trochu potácel
             vzadu po louce
             a z trávy mě sledovala černobílá kočka
             Byl to můj konec
             Najednou jsem viděl že k ní všechno vede
             a že se jí
             jak tam sedí
             nedokážu vyhnout

             Viděl jsem se jak natruc měním směr
             a mířím jinam
             jenom kvůli ní
             ale stejně průhledně marně
             zase jinam zase nazpátek

             Buď nepřímo k ní
             Nebo rovnou

             Uzel se stahoval dokud přede mnou neutekla

Uzel
zase jedno z těch slov

Sotva se za nějakým takovým pustím
už na jeho místě začne číhat něco
s čím jsem si vůbec nikdy neměl začínat

A pak už nepomůže ani škrt ani útěk
za jiným slovem
            Žádné není jiné
A všechna si to navzájem umějí připomenout

Necítím už báseň ale jen studený stisk
že nikdo z nás živých
by asi nechtěl doopravdy vědět
natož prožít
co může taky znamenat

            zaživa

            Dokud to přede mnou neuteče
            Jako tenkrát
"""

[translation-1]
title = "Alive"
translator = "Veronika Revická"
translator_level = "professional"
poem = """
I write about it
yet I don't want to think of it

I have no idea
why I always cling to one word
some such word
which makes me founder at last

„Did it happen to you when you were still   

           alive?“

            That afternoon I was wavering in it a little
            back in the meadow 
            and a black and white cat watched me from the grass
            It was the death of me
            Suddenly I saw that all led toward her
            and that I
            as she sat there
            couldn't avoid her

            I saw myself changing direction out of spite
            and heading elsewhere
            just because of her
            but still in that transparent vain manner
            elsewhere again back again

            Either indirectly toward her
            Or slap-bang

            The knot was getting tighter until she ran away from me

The knot
one of those words again

The instant I set off following one of its kind
something else starts lurking in its stead
which I never ever should have intrigued with

And then neither cut nor pursuit helps
of another word
There is no another
And they all are skilled in reminding each other of the fact

I no longer feel a poem but a cold clasp 
that none of us living
would not want to know for real
much less to live through
what could also mean

            alive

            Until it runs away from me
            Like then
"""