title = "Adagio"
author = "Jaroslav Vrchlický"
lang = "cs"
year = 1920
poem = """
Do velké, šedé škeble mramoru,
kde místo vody svadlé listí leží,
se kloní větve bříz a javorů.
Vše v dřímotě, jen mraky nebem běží.
Zde chtěl bych státi v zamyšlení dumném
a dívat se, jak večer táhne sem,
a luňák v letu posupném a šumném
jak po kořisti slídí nad lesem;
tou sochou chtěl bych býti kamennou,
jež o samotě dumá v lesní hloubi,
jež s větry mluví jen a ozvěnou,
na jejíž skráni s nocí den se snoubí.
"""

[translation-1]
title = "Adagio"
translator = "Paul Selver"
translator_level = "professional"
poem = """
Over the marble with its great drab shell,
Where faded leaves in place of water lie,
The boughs of birches and of maples fell:
All slumbers, save the scudding clouds on high.
Fain would I linger here in wistful poring,
And gaze at evening drawing nigh this way;
And at the hawk's gloom-covered, clamorous soaring,
How o'er the wood he watches for his prey;
Fain would I be this statue wrought in stone,
On loneliness in forest-depths to brood,
Speaking with winds and echo all alone,
Upon whose brow the night by day is wooed. 
"""